hdfc:
  credit:
    visa:
      otpSelector: "#txtOtpPassword"
      submitSelector: "button[type=submit]"
      failurePage: "ACSWeb/authJsp/authImprovedHopsTxnPage.jsp?transType=adsReg"
      successPage: "terminal.php"
  
